news_sites:
	washingtonpost:
		url: https://www.washingtonpost.com
		queries:
			homepage_article_links: '.headline a'
			article_body: '.topper-headline h1'
			article_title: 'article.paywall'
	elcolombiano:
		url: https://www.elcolombiano.com/
		queries:
			homepage_article_links: '.noticia-segundaria a'
			article_title: '.information-noticia h3'
			article_body: '.text'
